[agent.task_decomposition.model]
platform = "google-genai"
temperature = 0.1
max_tokens = 1000
apikey_name = "GOOGLE_API_KEY"

[agent.planner.model]
platform = "google-genai"
temperature = 0.1
max_tokens = 5000
apikey_name = "GOOGLE_API_KEY"

[agent.chat.model]
platform = "google-genai"
temperature = 0.1
max_tokens = 5000
apikey_name = "GOOGLE_API_KEY"

[agent.shortlister.model]
platform = "google-genai"
temperature = 0.1
max_tokens = 7000
apikey_name = "GOOGLE_API_KEY"

[agent.plan_controller.model]
platform = "google-genai"
temperature = 0.1
max_tokens = 6000
apikey_name = "GOOGLE_API_KEY"

[agent.final_answer.model]
platform = "google-genai"
temperature = 0.1
max_tokens = 15000
apikey_name = "GOOGLE_API_KEY"

[agent.code.model]
platform = "google-genai"
temperature = 0.1
max_tokens = 3000
apikey_name = "GOOGLE_API_KEY"

[agent.code_planner.model]
platform = "google-genai"
temperature = 0.1
max_tokens = 3000
apikey_name = "GOOGLE_API_KEY"

[agent.qa.model]
platform = "google-genai"
temperature = 0.1
max_tokens = 4000
apikey_name = "GOOGLE_API_KEY"

[agent.action.model]
platform = "google-genai"
temperature = 0.1
max_tokens = 400
apikey_name = "GOOGLE_API_KEY"
